/**
 * Static baseline data for pricing configuration.
 *
 * Used as the safe fallback when pricing config persistence is disabled.
 * Values sourced from:
 * - DTF matrix: pricing-contract.json tier matrix with open-ended final tier
 * - Additional prints: Live CMP DTF Labor workbook captured 2026-08-27
 *   (spreadsheet 1dtN83KQ2ERy6nozPJe65InaRvq0ydCdvUllTH9DtW9c)
 */
import "server-only";
import contract from "@/lib/fixtures/pricing-contract.json";
import type {
  DtfMatrixConfig,
  AdditionalPrintsConfig,
} from "./schemas";

export function getBaselineDtfMatrix(): DtfMatrixConfig {
  const contractTiers = contract.dtfEngine.tierPriceMatrix;
  return {
    lanes: [
      { key: "T1", label: "T1", margin: 0.50, active: true },
      { key: "T2", label: "T2", margin: 0.45, active: true },
      { key: "T3", label: "T3", margin: 0.40, active: true },
      { key: "T4", label: "T4", margin: 0.35, active: true },
    ],
    tiers: contractTiers.map((t, i) => ({
      tier: t.tier,
      minQty: t.minQty,
      // Final tier is open-ended (maxQty: null)
      maxQty: i === contractTiers.length - 1 ? null : t.maxQty,
      prices: { ...t.prices },
    })),
  };
}

export function getBaselineAdditionalPrints(): AdditionalPrintsConfig {
  return {
    services: [
      {
        key: "additional_large_print",
        name: "Additional Large Print",
        description: "A second large front or back print",
        type: "service",
        geometryKey: "FLAT_LARGE",
        composition: [{ sizeKey: "FLAT_LARGE", quantityPerShirt: 1 }],
        cogs: 2.905990959894806,
        operatorOperatingCost: 0.19397707100591716,
        enginePrice: 7,
        policyFloor: 0,
        manualOverride: 5,
        effectivePrice: 5,
        grossMargin: 0.41880180802103883,
        status: "Strategic override below engine",
        operatorMinPerShirt: 0,
        designerMinPerOrder: 5,
        active: true,
        sortOrder: 0,
      },
      {
        key: "sleeve_print",
        name: "Sleeve Print",
        description: "One standard sleeve print",
        type: "service",
        geometryKey: "FLAT_SLEEVE",
        composition: [{ sizeKey: "FLAT_SLEEVE", quantityPerShirt: 1 }],
        cogs: 2.1023624876725835,
        operatorOperatingCost: 0.19397707100591716,
        enginePrice: 6,
        policyFloor: 5,
        manualOverride: null,
        effectivePrice: 6,
        grossMargin: 0.6496062520545695,
        status: "Engine price",
        operatorMinPerShirt: 2,
        designerMinPerOrder: 5,
        active: true,
        sortOrder: 1,
      },
      {
        key: "bottom_upper_chest",
        name: "Bottom / Upper Chest",
        description: "Chest, yoke, or standard thigh print",
        type: "service",
        geometryKey: "FLAT_BOTTOM_CHEST",
        composition: [{ sizeKey: "FLAT_BOTTOM_CHEST", quantityPerShirt: 1 }],
        cogs: 1.6023624876725835,
        operatorOperatingCost: 0.19397707100591716,
        enginePrice: 4,
        policyFloor: 0,
        manualOverride: null,
        effectivePrice: 4,
        grossMargin: 0.5994093780818541,
        status: "Engine price",
        operatorMinPerShirt: 0,
        designerMinPerOrder: 5,
        active: true,
        sortOrder: 2,
      },
      {
        key: "vertical_print",
        name: "Vertical Print",
        description: "One vertical print location",
        type: "service",
        geometryKey: "FLAT_VERTICAL",
        composition: [{ sizeKey: "FLAT_VERTICAL", quantityPerShirt: 1 }],
        cogs: 2.6973745069033526,
        operatorOperatingCost: 0.19397707100591716,
        enginePrice: 7,
        policyFloor: 0,
        manualOverride: null,
        effectivePrice: 7,
        grossMargin: 0.6146607847280924,
        status: "Engine price",
        operatorMinPerShirt: 0,
        designerMinPerOrder: 5,
        active: true,
        sortOrder: 3,
      },
      {
        key: "name",
        name: "Name",
        description: "One personalized name",
        type: "service",
        geometryKey: "FLAT_NAME",
        composition: [{ sizeKey: "FLAT_NAME", quantityPerShirt: 1 }],
        cogs: 2.905990959894806,
        operatorOperatingCost: 0.19397707100591716,
        enginePrice: 7,
        policyFloor: 0,
        manualOverride: null,
        effectivePrice: 7,
        grossMargin: 0.5848584343007419,
        status: "Engine price",
        operatorMinPerShirt: 0,
        designerMinPerOrder: 5,
        active: true,
        sortOrder: 4,
      },
      {
        key: "number",
        name: "Number",
        description: "One personalized number",
        type: "service",
        geometryKey: "FLAT_NUMBER",
        composition: [{ sizeKey: "FLAT_NUMBER", quantityPerShirt: 1 }],
        cogs: 2.905990959894806,
        operatorOperatingCost: 0.19397707100591716,
        enginePrice: 7,
        policyFloor: 0,
        manualOverride: null,
        effectivePrice: 7,
        grossMargin: 0.5848584343007419,
        status: "Engine price",
        operatorMinPerShirt: 0,
        designerMinPerOrder: 5,
        active: true,
        sortOrder: 5,
      },
      {
        key: "name_number",
        name: "Name + Number",
        description: "One personalized name and number",
        type: "package",
        geometryKey: null,
        composition: [
          { sizeKey: "FLAT_NAME", quantityPerShirt: 1 },
          { sizeKey: "FLAT_NUMBER", quantityPerShirt: 1 },
        ],
        cogs: 4.767468030900722,
        operatorOperatingCost: 0.3879541420118343,
        enginePrice: 12,
        policyFloor: 0,
        manualOverride: null,
        effectivePrice: 12,
        grossMargin: 0.6027109974249398,
        status: "Engine price",
        operatorMinPerShirt: 0,
        designerMinPerOrder: 5,
        active: true,
        sortOrder: 6,
      },
      {
        key: "standard_package",
        name: "Standard Package",
        description: "Included large print + one additional large print",
        type: "package",
        geometryKey: null,
        composition: [{ sizeKey: "FLAT_LARGE", quantityPerShirt: 1 }],
        cogs: 3.118004848783695,
        operatorOperatingCost: 0.19397707100591716,
        enginePrice: 8,
        policyFloor: 0,
        manualOverride: null,
        effectivePrice: 8,
        grossMargin: 0.6102493939020381,
        status: "Engine price",
        operatorMinPerShirt: 0,
        designerMinPerOrder: 10,
        active: true,
        sortOrder: 7,
      },
      {
        key: "premium_package",
        name: "Premium Package",
        description:
          "Included large print + additional large + sleeve + name + number",
        type: "package",
        geometryKey: null,
        composition: [
          { sizeKey: "FLAT_LARGE", quantityPerShirt: 1 },
          { sizeKey: "FLAT_SLEEVE", quantityPerShirt: 1 },
          { sizeKey: "FLAT_NAME", quantityPerShirt: 1 },
          { sizeKey: "FLAT_NUMBER", quantityPerShirt: 1 },
        ],
        cogs: 6.784102728468112,
        operatorOperatingCost: 0.7759082840236686,
        enginePrice: 17,
        policyFloor: 0,
        manualOverride: 20,
        effectivePrice: 20,
        grossMargin: 0.6607948635765943,
        status: "Manual override",
        operatorMinPerShirt: 0,
        designerMinPerOrder: 10,
        active: true,
        sortOrder: 8,
      },
    ],
    columns: [
      { key: "name", label: "Service", required: true, visible: true, order: 0 },
      { key: "effectivePrice", label: "Price", required: true, visible: true, order: 1 },
      { key: "description", label: "Description", required: false, visible: true, order: 2 },
      { key: "type", label: "Type", required: false, visible: false, order: 3 },
      { key: "cogs", label: "COGS", required: false, visible: true, order: 4 },
      { key: "operatorOperatingCost", label: "Operating Cost", required: false, visible: false, order: 5 },
      { key: "enginePrice", label: "Engine Price", required: false, visible: true, order: 6 },
      { key: "policyFloor", label: "Policy Floor", required: false, visible: true, order: 7 },
      { key: "manualOverride", label: "Override", required: false, visible: true, order: 8 },
      { key: "grossMargin", label: "GM%", required: false, visible: true, order: 9 },
      { key: "status", label: "Status", required: false, visible: true, order: 10 },
      { key: "operatorMinPerShirt", label: "Op Min/Shirt", required: false, visible: false, order: 11 },
      { key: "designerMinPerOrder", label: "Des Min/Order", required: false, visible: false, order: 12 },
      { key: "geometryKey", label: "Geometry", required: false, visible: false, order: 13 },
    ],
    minimumBillableQuantity: 12,
  };
}
